POST https://aid-app-final-version.onrender.com/api/send-sos-email

Content-Type: application/json

{
  "senderEmail": "gonly7966@gmail.com",
  
  "recipients": ["mjeyashankar2005@gmail.com", "mjeyashankar189@gmail.com"],
  "message": "Test SOS message from REST Client"
}
